/**
 * This class is generated by jOOQ
 */
package com.renrenche.jqn.jooq.test.jooq.tables;


import com.renrenche.jqn.jooq.test.jooq.History;
import com.renrenche.jqn.jooq.test.jooq.Keys;
import com.renrenche.jqn.jooq.test.jooq.tables.records.StudentRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * 学生表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Student extends TableImpl<StudentRecord> {

    private static final long serialVersionUID = -394966370;

    /**
     * The reference instance of <code>history.student</code>
     */
    public static final Student STUDENT = new Student();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StudentRecord> getRecordType() {
        return StudentRecord.class;
    }

    /**
     * The column <code>history.student.id</code>. 学生id
     */
    public final TableField<StudentRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "学生id");

    /**
     * The column <code>history.student.name</code>. 学生姓名
     */
    public final TableField<StudentRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(11).nullable(false), this, "学生姓名");

    /**
     * The column <code>history.student.comment</code>. 评论
     */
    public final TableField<StudentRecord, String> COMMENT = createField("comment", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "评论");

    /**
     * Create a <code>history.student</code> table reference
     */
    public Student() {
        this("student", null);
    }

    /**
     * Create an aliased <code>history.student</code> table reference
     */
    public Student(String alias) {
        this(alias, STUDENT);
    }

    private Student(String alias, Table<StudentRecord> aliased) {
        this(alias, aliased, null);
    }

    private Student(String alias, Table<StudentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "学生表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return History.HISTORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<StudentRecord, Integer> getIdentity() {
        return Keys.IDENTITY_STUDENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StudentRecord> getPrimaryKey() {
        return Keys.KEY_STUDENT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StudentRecord>> getKeys() {
        return Arrays.<UniqueKey<StudentRecord>>asList(Keys.KEY_STUDENT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Student as(String alias) {
        return new Student(alias, this);
    }

    /**
     * Rename this table
     */
    public Student rename(String name) {
        return new Student(name, null);
    }
}
