spring:
  profiles:
    active: testing
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    property-naming-strategy: SNAKE_CASE
    timeZone: GMT+8
    deserialization:
      fail-on-unknown-properties: true
  aop:
    auto: true
    proxy-target-class: true
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  application:
    name: study
# jooq配置
jooq:
  sql-dialect: MySQL
logging:
  config: classpath:log4j2.yml