/**
 * This class is generated by jOOQ
 */
package com.renrenche.jqn.jooq.test.jooq;


import com.renrenche.jqn.jooq.test.jooq.tables.Student;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class History extends SchemaImpl {

    private static final long serialVersionUID = 1126912409;

    /**
     * The reference instance of <code>history</code>
     */
    public static final History HISTORY = new History();

    /**
     * 学生表
     */
    public final Student STUDENT = Student.STUDENT;

    /**
     * No further instances allowed
     */
    private History() {
        super("history", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Student.STUDENT);
    }
}
