/**
 * This class is generated by jOOQ
 */
package com.renrenche.jqn.study.jooq;


import com.renrenche.jqn.study.jooq.tables.Student;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in history
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 学生表
     */
    public static final Student STUDENT = com.renrenche.jqn.study.jooq.tables.Student.STUDENT;
}
