package com.mylg.study.drools.cashflow.execution;
import com.mylg.study.drools.cashflow.data.model.Account;
import com.mylg.study.drools.cashflow.data.model.AccountPeriod;
import com.mylg.study.drools.cashflow.data.model.CashFlow;
import com.mylg.study.drools.cashflow.data.model.CashFlowType;

dialect  "mvel"
rule "Increase balance for AccountPeriod Credits"
when
   ap : AccountPeriod( )
   $acc : Account( )
   CashFlow( type == CashFlowType.CREDIT,
             accountNo == $acc.accountNo,
             date >= ap.start && <= ap.end,
              $amount : amount)
then
   $acc.balance = $acc.balance + $amount;
end

rule "Decrease balance for AccountPeriod Debits"
when
   ap : AccountPeriod( )
   $acc : Account( )
   cf : CashFlow( type == CashFlowType.DEBIT, accountNo == $acc.accountNo, date >= ap.start && <= ap.end )
then
   $acc.balance = $acc.balance - cf.amount;
end

rule "Print blance for AccountPeriod" salience -50
when
       ap : AccountPeriod()
       $acc : Account( )
then
       System.out.println( "Account Number " + $acc.accountNo + " balance " + $acc.balance );
end
